spring.application.name=SmartTrip Backend

# ===============================
# MySQL Database
# ===============================

# MySQL Database - Railway
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Server
# ===============================

server.port=8080

# ===============================
# Google Gemini AI
# ===============================

gemini.api.key=${GEMINI_API_KEY}

# ===============================
# Groq AI
# ===============================

groq.api.key=${GROQ_API_KEY}