spring.application.name=SmartTrip Backend

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/smarttrip
spring.datasource.username=${root}
spring.datasource.password=${Cherry1006}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# Google Gemini AI
gemini.api.key=${AQ.Ab8RN6J-lb9sAF86TihmHU7yXqZwOsD2B18yY1rk4BZoewyPOQ}

# Groq api key
groq.api.key=${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}